# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(916, 706)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(300, 300))
        self.label_2.setStyleSheet("background-color: rgb(161, 204, 255);\n"
"background-color: rgb(147, 147, 147);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setMinimumSize(QtCore.QSize(150, 40))
        self.widget.setMaximumSize(QtCore.QSize(180, 16777215))
        self.widget.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")

        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget)

        self.user_temp = QtWidgets.QLabel(Form)
        self.user_temp.setObjectName("user_temp")
        self.verticalLayout.addWidget(self.user_temp)

        self.pre_loading = QtWidgets.QPushButton(Form)
        self.pre_loading.setObjectName("pre_loading")
        self.verticalLayout.addWidget(self.pre_loading)

        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout.addWidget(self.pushButton_1)

        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.area_data = QtWidgets.QPushButton(Form)
        self.area_data.setObjectName("area_data")
        self.verticalLayout.addWidget(self.area_data)

        self.user_data = QtWidgets.QPushButton(Form)
        self.user_data.setObjectName("user_data")
        self.verticalLayout.addWidget(self.user_data)

        self.test_temp = QtWidgets.QPushButton(Form)
        self.test_temp.setObjectName("test_temp")
        self.verticalLayout.addWidget(self.test_temp)

        self.open_voice = QtWidgets.QPushButton(Form)
        self.open_voice.setObjectName("open_voice")
        self.verticalLayout.addWidget(self.open_voice)

        self.info_save = QtWidgets.QPushButton(Form)
        self.info_save.setObjectName("info_save")
        self.verticalLayout.addWidget(self.info_save)

        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "人脸识别"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">体温数据管理系统</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.user_temp.setText(_translate("Form", "体温"))
        self.pre_loading.setText(_translate("Form", "预加载"))
        self.pushButton_1.setText(_translate("Form", "进行匹配"))
        self.pushButton_2.setText(_translate("Form", "关闭摄像头"))
        self.area_data.setText(_translate("Form", "区域数据统计界面"))
        self.user_data.setText(_translate("Form", "个人数据统计界面"))
        self.test_temp.setText(_translate("Form", "测温"))
        self.open_voice.setText(_translate("Form", "播报"))
        self.info_save.setText(_translate("Form", "保存"))
