# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '区域数据统计.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget

import imag

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-image: url(:/imgTest/bg1.jpg);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 30, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(70, 60, 261, 121))
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 210, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(50, 270, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(130, 210, 121, 21))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(130, 240, 121, 21))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(130, 270, 121, 21))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(270, 260, 112, 32))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "该时段温度数据分析"))
        self.label_2.setText(_translate("Form", "平均温度："))
        self.label_3.setText(_translate("Form", "总人数："))
        self.label_4.setText(_translate("Form", "该地区风险："))
        self.pushButton.setText(_translate("Form", "返回主界面"))

if __name__ == "__main__":
	app = QApplication(sys.argv)
	form = QWidget()
	w = Ui_Form()
	w.setupUi(form)
	form.show()
	sys.exit(app.exec_())