# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '区域数据统计.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bgimag
import imag


class Ui_FormPart(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 395)
        #Form.setStyleSheet("background-image: url(:/imgTest/bg1.jpg);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(250, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label.setFont(font)
        #self.label.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.label.setObjectName("label")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(110, 70, 421, 151))
        #self.listView.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.listView.setObjectName("listView")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(80, 250, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_2.setFont(font)
        #self.label_2.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(80, 290, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_3.setFont(font)
        #self.label_3.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 330, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_4.setFont(font)
        #self.label_4.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.label_4.setObjectName("label_4")
        self.pushButton2 = QtWidgets.QPushButton(Form)
        self.pushButton2.setGeometry(QtCore.QRect(460, 340, 112, 32))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.pushButton2.setFont(font)
        self.pushButton2.setMouseTracking(True)
        #self.pushButton2.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.pushButton2.setObjectName("pushButton2")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(170, 250, 104, 31))
        #self.textBrowser.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(170, 290, 104, 31))
        #self.textBrowser_2.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(170, 330, 104, 31))
        #self.textBrowser_3.setStyleSheet("background-image: url(:/Test/bgimg/bg3.jpeg);")
        self.textBrowser_3.setObjectName("textBrowser_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "该时段温度数据分析"))
        self.label_2.setText(_translate("Form", "平均温度   ："))
        self.label_3.setText(_translate("Form", "总人数       ："))
        self.label_4.setText(_translate("Form", "该地区风险："))
        self.pushButton2.setText(_translate("Form", "返回主界面"))
