# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '用户数据模块.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget

import imag

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setStyleSheet("background-image: url(:/imgTest/bg1.jpg);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 190, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(20, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(80, 190, 100, 16))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(80, 220, 100, 16))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.listView = QtWidgets.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(30, 40, 131, 131))
        self.listView.setObjectName("listView")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(140, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(220, 190, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(220, 220, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(220, 250, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(270, 190, 100, 16))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(270, 220, 100, 16))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_5.setGeometry(QtCore.QRect(270, 250, 100, 16))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.listView_2 = QtWidgets.QListView(Form)
        self.listView_2.setGeometry(QtCore.QRect(200, 40, 191, 131))
        self.listView_2.setObjectName("listView_2")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "姓名："))
        self.label_2.setText(_translate("Form", "用户ID："))
        self.pushButton.setText(_translate("Form", "生成图表"))
        self.label_3.setText(_translate("Form", "该用户近期温度变化"))
        self.label_4.setText(_translate("Form", "最大值："))
        self.label_5.setText(_translate("Form", "最小值："))
        self.label_6.setText(_translate("Form", "平均值："))
        self.pushButton_2.setText(_translate("Form", "返回主界面"))

if __name__ == "__main__":
	app = QApplication(sys.argv)
	form = QWidget()
	w = Ui_Form()
	w.setupUi(form)
	form.show()
	sys.exit(app.exec_())