# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '输入界面.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import bgimag
import imag


class Ui_FormInput(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 395)
        #Form.setStyleSheet("background-image: url(:/imgTest/bg1.jpg);")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(190, 160, 271, 40))
        #self.textEdit.setStyleSheet("background-image: url(:/Test/bgimg/bg5.jpg);")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 50, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(18)
        self.label.setFont(font)
        #self.label.setStyleSheet("background-image: url(:/Test/bgimg/bg5.jpg);")
        self.label.setObjectName("label")
        self.pushButton3 = QtWidgets.QPushButton(Form)
        self.pushButton3.setGeometry(QtCore.QRect(270, 300, 112, 32))
        font = QtGui.QFont()
        font.setFamily("Yuppy SC")
        font.setPointSize(14)
        self.pushButton3.setFont(font)
        self.pushButton3.setMouseTracking(True)
        #self.pushButton3.setStyleSheet("background-image: url(:/Test/bgimg/bg5.jpg);")
        self.pushButton3.setObjectName("pushButton3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "请输入您想查询的用户ID"))
        self.pushButton3.setText(_translate("Form", "确认"))
